# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WF-NpARZ8LTwvVx7gTgaXliiq_TIbu-1
"""

print('Silas Oliveira')

x = 10
y = 5
print("O total da soma é: ", x + y)
print("O total da subtração é: ", x - y)
print("O total da multiplicação é: ", x * y)
print("O total da divisão é: ", x / y)

# == teste da variável
# > maior que
# < menor que
# >= maior igual
# <= menor igual
# != diferente de
n1 = 10
n2 = 2
if(n2 == 0):
  print('o denominador não pode ser 0')
else:
  result = n1 / n2
print(result)

from datetime import date
ano_corrente = date.today().year
ano_nascimento = 1980
idade = ano_corrente - ano_nascimento

if(idade <= 25):
  print('Voce é novinho, tem ', idade, ' anos')
else:
  print('Você é experiente, tem ', idade, ' anos')

def avaliar_experiencia(ano_nascimento):
  if(type(ano_nascimento) != str):
    ano_corrente = 2021
    idade = ano_corrente - ano_nascimento

    if(idade <= 25):
      print('Voce é novinho, tem ', idade, ' anos')
    else:
      print('Você é experiente, tem ', idade, ' anos')
  else:
    print('O valor deve ser numérico')

avaliar_experiencia('Silas')